#pragma once
#include "simde/orbital_spaces/atomic_orbitals.hpp"
#include "simde/orbital_spaces/auxiliary_basis_set.hpp"
#include "simde/orbital_spaces/complimentary_auxiliary_basis_set.hpp"
#include "simde/orbital_spaces/density_fit_basis.hpp"
#include "simde/orbital_spaces/localized_orbitals.hpp"
#include "simde/orbital_spaces/paos.hpp"
#include "simde/orbital_spaces/qc_mos.hpp"
#include "simde/orbital_spaces/resolution_of_the_identity_basis_set.hpp"
