#pragma once
#include "property_types/ao_integrals/f12/b.hpp"
#include "property_types/ao_integrals/f12/correlation_factor.hpp"
#include "property_types/ao_integrals/f12/correlation_factor_squared.hpp"
#include "property_types/ao_integrals/f12/coupling_coefficient.hpp"
#include "property_types/ao_integrals/f12/dfdr_squared.hpp"
#include "property_types/ao_integrals/f12/gr.hpp"
#include "property_types/ao_integrals/f12/v.hpp"
#include "property_types/ao_integrals/f12/x.hpp"